import { createUploadthing, type FileRouter } from "uploadthing/next";
import { auth } from "../auth/auth";
import prisma from "@/lib/prisma";
import { ingestPDF } from "../rag/ingest";
// import { getServerSession } from "next-auth"; 
// import { authOptions } from "@/services/auth/authOptions"; 
// import prisma from "@/lib/prisma";

const f = createUploadthing();


export const ourFileRouter = {

  pdfUploader: f({ pdf: { maxFileSize: "16MB", maxFileCount: 1 } })

    .middleware(async ({ req }) => {
      const session = await auth();
     
      if (!session?.user) throw new Error("Unauthorized");
      
     return { userId: session.user.id };
    })
    
  
    .onUploadComplete(async ({ metadata, file }) => {
      console.log("Upload complete for userId:", metadata.userId);
      console.log("File URL generated by UploadThing:", file.ufsUrl);


      const doc = await prisma.document.create({
        data: {
          userId: metadata.userId,
          name: file.name,
          fileUrl: file.ufsUrl,
          chunkCount : 0,
          status: "PENDING" 
        }
      });

      // 2. Trigger your ingestion logic (Mistral embeddings, Pinecone) asynchronously
      // Do NOT await the heavy Pinecone stuff here, or Vercel will timeout!
      // startPineconeIngestion(file.url, metadata.userId); 
 
      await ingestPDF(file.ufsUrl, metadata.userId, file.name, doc.id);
      // Whatever is returned here is sent back to the frontend Dropzone component
      return { uploadedBy: metadata.userId, url: file.ufsUrl };
    }),
} satisfies FileRouter;

export type OurFileRouter = typeof ourFileRouter;